#EUREKA CONFIG
eureka:
  instance:
    hostname: localhost
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://registry-service:8070/eureka/

spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: false

#
#APP CONFIG


server:
  port: 9908
