#HEATH CHECK CONFIG
management:
  health:
    diskspace:
      enabled: true
    db:
      enabled: false
  endpoint:
    health:
      enabled: true
      show-details: always
  endpoints:
    enabled-by-default: false
    web:
      base-path: /

#
#EUREKA CONFIG
eureka:
  instance:
    hostname: localhost
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: false

#
#APP CONFIG


server:
  port: 9908
