#HEATH CHECK CONFIG
management:
  endpoints:
    web:
      exposure:
        include: "*"

#
#EUREKA CONFIG
eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

#GATEWAY CONFIG
spring:
  cloud:
#    loadbalancer.ribbon.enabled: false
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: openapi
          uri: http://localhost:${server.port}
          predicates:
            - Path=/v3/api-docs/**
          filters:
            - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs

        - id: organization-service
          uri: lb://organization-service
          predicates:
            - Path=/organizations/**
          filters:
            - RewritePath=/organizations/(?<path>.*), /$\{path}
            - RemoveRequestHeader= Cookie,Set-Cookie

        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/products/**
          filters:
            - RewritePath=/products/(?<path>.*), /$\{path}
            - RemoveRequestHeader= Cookie,Set-Cookie
#
#APP CONFIG
app:
  version: 1.0.0

server:
  port: 8072
#
#logging:
#  config: classpath:logback-delayed.xml
springdoc:
  enable-native-support: true
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - name: organization
        url: /v3/api-docs/organization
      - name: product
        url: /v3/api-docs/product
