#HEATH CHECK CONFIG
management:
  endpoints:
    web:
      exposure:
        include: "*"

#
#EUREKA CONFIG
eureka:
  instance:
    hostname: localhost
#    preferIpAddress: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

#GATEWAY CONFIG
spring:
  cloud:
    loadbalancer.ribbon.enabled: false
    gateway:
      routes:
        - id: organization-service
          uri: lb://organization-service
          predicates:
            - Path=/organizations/**
          filters:
            - RewritePath=/organizations/(?<path>.*), /$\{path}
            - RemoveRequestHeader= Cookie,Set-Cookie
            -
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/products/**
          filters:
            - RewritePath=/products/(?<path>.*), /$\{path}
            - RemoveRequestHeader= Cookie,Set-Cookie
#
#APP CONFIG
app:
  version: 1.0.0

server:
  port: 8072
#
#logging:
#  config: classpath:logback-delayed.xml

