#EUREKA CONFIG
eureka:
  instance:
    hostname: localhost
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://registry-service:8070/eureka/

spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: false

#
#APP CONFIG
app:
  version: 1.0.0
  jwt_secret: "{cipher}213e68f3e824a5bb0d26e2b21fea6d8747c9ad229c6452665dee3d76dcf6e79dcba430df3fb1cbe85dab485cd32854d33490aae3aa2622d0d3dfbbef98f6873399c5a7247599a29e0352af65b28e0d70b93aba82a4174a35ff75868b3fca6e468898c350e1535299d19d31c647ac48e3"

server:
  port: 8080
