spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/GstudyOrganization
    username: "{cipher}f84e9d0d45b868a41d1723c3228dd21540958aff43f980f19b824572bf6b5946"
    password: "{cipher}6c58cffa32a4aff62c0bcacb2b1d62bce565671f58ffa65e0ad4fb7c6200df2c"
  jpa:
    properties:
      hibernate:
        default_schema: public
    hibernate:
      ddl-auto: update