spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/GstudyOrganization"
    username: "{cipher}4d4e81c8fb52ff2733d6f30ab8bf498addfdd7c849ac898ff4ff9f9f1e38fe86"
    password: "{cipher}f6b4199f134b21c3728badc009ab9f7ac1073c06496099ba4709f43f4d27fd6b"
  jpa:
    properties:
      hibernate:
        default_schema: public
    hibernate:
      ddl-auto: update