spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/GstudyProduct
    username: {cipher}9b61c1fbaf567592c0f5cb67a7b4e793dad1763cca16437374015296c575e260
    password: {cipher}b720dbd7e90005b882eeac60272b34a9a6cb6adca6e20a9ad6bae7609af0dbf7
  jpa:
    properties:
      hibernate:
        default_schema: public
#    hibernate:
#      ddl-auto: create-drop
