spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/GstudyProduct"
    username: "{cipher}d4016c3ec154d71035327ffabb6e6c61b1e0a65925d9bfdd29371e1794ea39f0"
    password: "{cipher}71bfa91199fb00fb96f551fd768f1a4124f276e1a6a5ffd1fa2bd46ce82e0930"
  jpa:
    properties:
      hibernate:
        default_schema: public
    hibernate:
      ddl-auto: update  
